[package]
name = "dtp-core"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
documentation.workspace = true

[dependencies]
sui-sdk.workspace = true

[dev-dependencies]
cargo-husky.workspace = true