[package]
name = "dtp-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
# Put sui code at same level where DTP directory is located:
# Example:
#    /home/johndoe/someproject/sui
#    /home/johndoe/someproject/dtp

