#!/bin/bash

# Equivalent to sui, but for targeting remote devnet network only.

NETNAME="devnet"
SUI_REPO_BRANCH="devnet"
SUI_SCRIPT="dsui"

# Just find the absolute path of the "dtp-dev" where most
# dependencies will be downloaded and build/runtime files
# will be located.
SCRIPT_READLINK="$(readlink -f "$0")"
SCRIPT_NAME="$(basename $SCRIPT_READLINK)"
SCRIPT_DIR="$(dirname $SCRIPT_READLINK)"
source "$SCRIPT_DIR/script_common" "$SCRIPT_DIR" "$SCRIPT_NAME" "$NETNAME" "$SUI_REPO_BRANCH"

check_dev_setup

# Use the proper config automatically.
SUI_SUBCOMMAND=$1
if [[ "$1" = "client" || "$1" == "console" ]]; then  
  shift 1
  "$SUI_BIN_DIR"/sui $SUI_SUBCOMMAND --client.config "$CLIENT_CONFIG" "$@"
  exit
fi

if [[ "$1" == "network" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    "$SUI_BIN_DIR"/sui network --help
  fi
  echo
  echo "network command not supported by dsui for remote devnet. Try with sui directly if you think it should work!?"
  exit
fi

if [[ "$1" == "genesis" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    "$SUI_BIN_DIR"/sui genesis --help
  fi
  echo
  echo "genesis command not supported by dsui for remote devnet. Try with sui directly if you think it should work!?"
fi

if [[ "$1" == "start" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    "$SUI_BIN_DIR"/sui start --help
  fi
  echo
  echo
  echo "start command not supported by dsui for remote devnet. Try with sui directly if you think it should work!?"
fi

if [[ "$1" == "keytool" ]]; then
  shift 1
  "$SUI_BIN_DIR"/sui $SUI_SUBCOMMAND --keystore-path "$KEYSTORE_FILE" "$@"
  exit
fi

# Default
"$SUI_BIN_DIR"/sui "$@"
