#!/bin/bash

# If not already done:
#  - Get devnet binaries and build it under dtp-dev/sui-devnet
#  - Initialize the user keystore under dtp-dev/devnet 
#
NETNAME="devnet"
SUI_REPO_BRANCH="devnet"
SUI_SCRIPT="dsui"

# Call the initialization code common to all script.
SCRIPT_READLINK="$(readlink -f "$0")"
SCRIPT_NAME="$(basename $SCRIPT_READLINK)"
SCRIPT_DIR="$(dirname $SCRIPT_READLINK)"
source "$SCRIPT_DIR/script_common" "$SCRIPT_DIR" "$SCRIPT_NAME" "$NETNAME" "$SUI_REPO_BRANCH"

common_init_dev_setup

build_sui_repo_branch

echo Remember:
echo "  Use \"$SUI_SCRIPT\" to access $NETNAME"
echo
echo Try it by typing \"$SUI_SCRIPT client gas\"
