#!/bin/bash

# Equivalent to sui, but target the localnet and its proper config files (network.yaml and client.yaml)

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }

# Just find the absolute path of the "workspace"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
WS_DIR_REL="$SCRIPT_DIR/../workspace"
WS_DIR="$(cd "$(dirname "$WS_DIR_REL")"; pwd)/$(basename "$WS_DIR_REL")"

# TODO Validate if workspace and sui binary are correct and give advises if not.

# Use the proper config automatically.
$WS_DIR/sui/target/debug/sui client --client.config "$WS_DIR/localnet/client.yaml" "$@"