#!/bin/bash

# Equivalent to sui, but target the localnet and its proper config files (network.yaml and client.yaml)

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }

# Just find the absolute path of the "dtp-dev"
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
WS_DIR_REL="$SCRIPT_DIR/../../dtp-dev"
WS_DIR="$(cd "$(dirname "$WS_DIR_REL")"; pwd)/$(basename "$WS_DIR_REL")"

# TODO Validate if dtp-dev and sui binary are correct and give advises if not.

# Use the proper config automatically.
SUI_SUBCOMMAND=$1
if [[ "$1" = "client" || "$1" == "console" ]]; then  
  shift 1
  $WS_DIR/sui/target/debug/sui $SUI_SUBCOMMAND --client.config "$WS_DIR/localnet/client.yaml" "$@"
  exit
fi

if [[ "$1" == "network" ]]; then
  shift 1
  $WS_DIR/sui/target/debug/sui $SUI_SUBCOMMAND --network.config "$WS_DIR/localnet/network.yaml" "$@"
  exit
fi

if [[ "$1" == "genesis" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $WS_DIR/sui/target/debug/sui genesis --help
  fi
  echo
  setup_error "Error: Use dtp/script/init-localnet instead for re-initializing localnet"
fi

if [[ "$1" == "start" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $WS_DIR/sui/target/debug/sui start --help
  fi
  echo
  # TODO Consider implementing a start-localnet script instead.
  setup_error "Error: Use dtp/script/init-localnet instead for re-initializing localnet"
fi

if [[ "$1" == "keytool" ]]; then
  shift 1
  $WS_DIR/sui/target/debug/sui $SUI_SUBCOMMAND --keystore-path "$WS_DIR/localnet/sui.keystore" "$@"
  exit
fi

# Default
$WS_DIR/sui/target/debug/sui "$@"