#!/bin/bash

# Equivalent to sui, but target the localnet and its proper config files (network.yaml and client.yaml)

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }

# Just find the absolute path of the "dtp-dev"
SCRIPT_READLINK="$(readlink -f "$0")"
SCRIPT_NAME="$(basename $SCRIPT_READLINK)"
SCRIPT_DIR="$(dirname $SCRIPT_READLINK)"
DEV_DIR_REL="$SCRIPT_DIR/../../dtp-dev"
DEV_DIR="$(cd "$(dirname "$DEV_DIR_REL")"; pwd)/$(basename "$DEV_DIR_REL")"

# Some other commonly used locations.
SUI_BIN_DIR="$DEV_DIR/sui-devnet/target/debug"

# Files often needed for sui CLI calls
NETWORK_CONFIG="$DEV_DIR/localnet/network.yaml"
CLIENT_CONFIG="$DEV_DIR/localnet/client.yaml"
KEYSTORE_FILE="$DEV_DIR/localnet/sui.keystore"

# TODO Validate if dtp-dev and sui binary are correct and give advises if not.

# Use the proper config automatically.
SUI_SUBCOMMAND=$1
if [[ "$1" = "client" || "$1" == "console" ]]; then  
  shift 1
  $SUI_BIN_DIR/sui $SUI_SUBCOMMAND --client.config "$CLIENT_CONFIG" "$@"
  exit
fi

if [[ "$1" == "network" ]]; then
  shift 1
  $SUI_BIN_DIR/sui $SUI_SUBCOMMAND --network.config "$NETWORK_CONFIG" "$@"
  exit
fi

if [[ "$1" == "genesis" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $SUI_BIN_DIR/sui genesis --help
  fi
  echo
  setup_error "Error: Use dtp/script/init-localnet instead for re-initializing localnet"
fi

if [[ "$1" == "start" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $SUI_BIN_DIR/sui start --help
  fi
  echo
  # TODO Consider implementing a start-localnet script instead.
  setup_error "Error: Use dtp/script/init-localnet instead for re-initializing localnet"
fi

if [[ "$1" == "keytool" ]]; then
  shift 1
  $SUI_BIN_DIR/sui $SUI_SUBCOMMAND --keystore-path "$KEYSTORE_FILE" "$@"
  exit
fi

# Default
$SUI_BIN_DIR/sui "$@"
