#!/bin/bash

# Do not call this script directly. It is a "common script" called by the other scripts.
#
# It initializes a bunch of environment variable, verify that some initialization took 
# place, identify some common user errors etc...

# DTP does not work with version below these.
MIN_SUI_VERSION="sui 0.22.0"
MIN_RUST_VERSION="rustc 1.65.0"

# Mandatory command line input
SCRIPT_DIR=$1
SCRIPT_NAME=$2
NETNAME=$3
SUI_REPO_BRANCH=$4

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }
export -f setup_error
version_greater_equal() { printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort; }
export -f version_greater_equal
script_cmd() { script -efqa "$SCRIPT_OUTPUT" -c "$*"; }
export -f script_cmd
beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
export -f beginswith

# Directories
DEV_DIR_REL="$SCRIPT_DIR/../../dtp-dev"
DEV_DIR="$(cd "$(dirname "$DEV_DIR_REL")"; pwd)/$(basename "$DEV_DIR_REL")"
MOVE_SRC_DIR_REL="$SCRIPT_DIR/../move"
MOVE_SRC_DIR="$(cd "$(dirname "$MOVE_SRC_DIR_REL")"; pwd)/$(basename "$MOVE_SRC_DIR_REL")"
LOCAL_BIN="$HOME/.local/bin"

# Some other commonly used locations.
SUI_REPO_DIR="$DEV_DIR/sui-$SUI_REPO_BRANCH-branch"
SUI_BIN_DIR="$SUI_REPO_DIR/target/debug"
GENESIS_DATA_DIR="$SCRIPT_DIR/genesis_data"

NETWORK_DATA_DIR="$DEV_DIR/user-$NETNAME"
PUBLISH_DATA_DIR="$NETWORK_DATA_DIR/published_data"

# Configuration files (often needed for sui CLI calls)
NETWORK_CONFIG="$NETWORK_DATA_DIR/network.yaml"
CLIENT_CONFIG="$NETWORK_DATA_DIR/client.yaml"

SCRIPT_OUTPUT="$PUBLISH_DATA_DIR/publish_output.txt"
PACKAGE_ID_OUTPUT="$PUBLISH_DATA_DIR/package_id.txt"
CLIENT_ADDRESSES_OUTPUT="$PUBLISH_DATA_DIR/client_addresses.txt"

update_bin_path() { 
  UBP_SRC_DIR="$HOME/.local/bin"
  UBP_TARGET="$SCRIPT_DIR/$1"
  if [ -d "$UBP_SRC_DIR" ]; then
    if [ ! -L "$UBP_SRC_DIR/$1" ]; then
      ln -s "$UBP_TARGET" "$UBP_SRC_DIR/$1"
      echo "Symlink added: $UBP_SRC_DIR/$1 -> $UBP_TARGET"
    else
      # Verify link is as intended, if not replace it.
      UBP_READLINK=$( readlink -f "$UBP_SRC_DIR/$1" )
      if [[ "$UBP_READLINK" != "$UBP_TARGET" ]]; then
         ln -sf "$UBP_TARGET" "$UBP_SRC_DIR/$1"
         echo "Symlink updated: $UBP_SRC_DIR/$1 -> $UBP_TARGET"
         # If the target is the called script, then replace
         # it and exit (will force user to re-execute from the
         # new link, potentially being a different script version).
         if [[ "$1" == "$SCRIPT_NAME" ]]; then
           setup_error "Retry $1 again (in case the new synlink point to a new version)"
        fi
      fi
    fi
  fi
}
export -f update_bin_path

build_sui_repo_branch() {

  # Verify Sui pre-requisites are installed.
  which curl &> /dev/null || setup_error "Need to install curl. See https://docs.sui.io/build/install#prerequisites";
  which git &> /dev/null || setup_error "Need to install git. See https://docs.sui.io/build/install#prerequisites";
  which cmake &> /dev/null || setup_error "Need to install cmake. See https://docs.sui.io/build/install#prerequisites";
  which rustc &> /dev/null || setup_error "Need to install rust. See https://docs.sui.io/build/install#prerequisites";
  which cargo &> /dev/null || setup_error "Need to install cargo. See https://docs.sui.io/build/install#prerequisites";

  # Verify Rust is recent enough.
  version_greater_equal "$(rustc --version)" "$MIN_RUST_VERSION" || setup_error "Upgrade rust to a more recent version";

  # If not already done, get the github sui $SUI_REPO_BRANCH.
  if [ ! -d "$DEV_DIR/sui-$SUI_REPO_BRANCH-branch" ]
  then
    git clone -b devnet https://github.com/MystenLabs/sui.git "$DEV_DIR/sui-$SUI_REPO_BRANCH-branch"  || setup_error "Failed getting Sui $SUI_REPO_BRANCH branch from github";
  fi

  # Update sui devnet local repo (if needed)
  (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch && git remote update >& /dev/null)
  V1=$(cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch; git rev-parse HEAD)
  V2=$(cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch; git rev-parse '@{u}')
  if [ $V1 != $V2 ]
  then 
    # Does a bit more than needed, but should allow to recover
    # from most operator error...
    echo Updating sui $NETNAME in dtp-dev...
    (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch && git switch $SUI_REPO_BRANCH > /dev/null)
    (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch && git fetch > /dev/null)
    (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch && git reset --hard origin/$SUI_REPO_BRANCH > /dev/null)
    (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch && git merge '@{u}')
  fi

  # Verify sui built is latest.
  echo Building $NETNAME using latest Sui $SUI_REPO_BRANCH branch...
  (cd $DEV_DIR/sui-$SUI_REPO_BRANCH-branch; cargo build)

  # Sanity test that the sui binary works
  if [ ! -f "$SUI_BIN_DIR/sui" ]; then
    setup_error "$SUI_BIN_DIR/sui binary not found"
  fi

  SUI_VERSION=$($SUI_BIN_DIR/sui --version)
  if [ -z "$SUI_VERSION" ]; then
    setup_error "$SUI_BIN_DIR/sui --version not running properly"
  fi

  # Check if sui is recent enough.
  version_greater_equal "$SUI_VERSION" "$MIN_SUI_VERSION" || setup_error "Sui binary version too old (not supported)"

}

export -f build_sui_repo_branch

check_dev_setup() {
  # Sanity check the development setup is OK.
  if [ ! -d "$DEV_DIR" ]; then
    setup_error "$DEV_DIR missing. Please run 'dtp/script/init-$NETNAME'"
  fi

  if [ ! -d "$DEV_DIR/sui-$SUI_REPO_BRANCH-branch" ]; then
    setup_error "$DEV_DIR/sui-$SUI_REPO_BRANCH-branch missing. Please run 'dtp/script/init-$NETNAME'"
  fi

  if [ ! -d "$DEV_DIR/user-$NETNAME" ]; then
    setup_error "$DEV_DIR/user-$NETNAME missing. Please run 'dtp/script/init-$NETNAME'"
  fi
}

export -f check_dev_setup

common_init_dev_setup() {
  # This is intended to be a fast initialization setup, and
  # no-op if already all setup. Intent is just to fix symlinks if
  # user did accidently deleted them and save the day.
  mkdir -p "$DEV_DIR"
  mkdir -p "$DEV_DIR/user-$NETNAME"

  update_bin_path "init-localnet"
  update_bin_path "init-testnet"
  update_bin_path "init-devnet"
  update_bin_path "lsui"
  update_bin_path "tsui"
  update_bin_path "dsui"
  update_bin_path "publish-localnet"
  update_bin_path "publish-testnet"
  update_bin_path "publish-devnet"

  echo "Output location = $DEV_DIR"
}
export -f common_init_dev_setup