#!/bin/bash

# Do not call this script directly. It is a "common script" called by the other scripts.
#
# It initializes a bunch of environment variable, verify that some initialization took 
# place, identify some common user errors etc...

# DTP does not work with version below these.
MIN_SUI_VERSION="sui 0.22.0"
MIN_RUST_VERSION="rustc 1.65.0"

# Mandatory command line input
SCRIPT_DIR=$1
SCRIPT_NAME=$2
NETNAME=$3
SUI_REPO_BRANCH=$4

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }
export -f setup_error
version_greater_equal() { printf '%s\n%s\n' "$2" "$1" | sort --check=quiet --version-sort; }
export -f version_greater_equal
script_cmd() { script -efqa "$SCRIPT_OUTPUT" -c "$*"; }
export -f script_cmd
beginswith() { case $2 in "$1"*) true;; *) false;; esac; }
export -f beginswith

# Directories
DEV_DIR_REL="$SCRIPT_DIR/../../dtp-dev"
DEV_DIR="$(cd "$(dirname "$DEV_DIR_REL")"; pwd)/$(basename "$DEV_DIR_REL")"
MOVE_SRC_DIR_REL="$SCRIPT_DIR/../move"
MOVE_SRC_DIR="$(cd "$(dirname "$MOVE_SRC_DIR_REL")"; pwd)/$(basename "$MOVE_SRC_DIR_REL")"
LOCAL_BIN="$HOME/.local/bin"

# Some other commonly used locations.
SUI_REPO_DIR="$DEV_DIR/sui-$SUI_REPO_BRANCH"
SUI_BIN_DIR="$SUI_REPO_DIR/target/debug"
GENESIS_DATA_DIR="$SCRIPT_DIR/genesis_data"
PUBLISH_DATA_DIR="$DEV_DIR/publish_data/$NETNAME"

# Configuration files (often needed for sui CLI calls)
NETWORK_CONFIG="$DEV_DIR/$NETNAME/network.yaml"
CLIENT_CONFIG="$DEV_DIR/$NETNAME/client.yaml"

SCRIPT_OUTPUT="$PUBLISH_DATA_DIR/publish_output.txt"
PACKAGE_ID_OUTPUT="$PUBLISH_DATA_DIR/package_id.txt"
CLIENT_ADDRESSES_OUTPUT="$PUBLISH_DATA_DIR/client_addresses.txt"

update_bin_path() { 
  UBP_SRC_DIR="$HOME/.local/bin"
  UBP_TARGET="$SCRIPT_DIR/$1"
  if [ -d "$UBP_SRC_DIR" ]; then
    if [ ! -L "$UBP_SRC_DIR/$1" ]; then
      ln -s "$UBP_TARGET" "$UBP_SRC_DIR/$1"
      echo "Symlink added: $UBP_SRC_DIR/$1 -> $UBP_TARGET"
    else
      # Verify link is as intended, if not replace it.
      UBP_READLINK=$( readlink -f "$UBP_SRC_DIR/$1" )
      if [[ "$UBP_READLINK" != "$UBP_TARGET" ]]; then
         ln -sf "$UBP_TARGET" "$UBP_SRC_DIR/$1"
         echo "Symlink updated: $UBP_SRC_DIR/$1 -> $UBP_TARGET"
         # If the target is the called script, then replace
         # it and exit (will force user to re-execute from the
         # new link, potentially being a different script version).
         if [[ "$1" == "$SCRIPT_NAME" ]]; then
           setup_error "Retry $1 again (in case the new synlink point to a new version)"
        fi
      fi
    fi
  fi
}
export -f update_bin_path

# Sanity check the development setup is OK.
if [ ! -d "$DEV_DIR" ]; then
  setup_error "$DEV_DIR missing. Please run 'dtp/script/init-$NETNAME'"
fi

if [ ! -d "$DEV_DIR/sui-$SUI_REPO_BRANCH" ]; then
  setup_error "$DEV_DIR/sui-$SUI_REPO_BRANCH missing. Please run 'dtp/script/init-$NETNAME'"
fi

if [ ! -d "$DEV_DIR/$NETNAME" ]; then
  setup_error "$DEV_DIR/$NETNAME missing. Please run 'dtp/script/init-$NETNAME'"
fi

update_bin_path "init-localnet"
update_bin_path "init-testnet"
update_bin_path "init-devnet"
update_bin_path "lsui"
update_bin_path "tsui"
update_bin_path "dsui"
update_bin_path "publish-localnet"
update_bin_path "publish-testnet"
update_bin_path "publish-devnet"