#!/bin/bash

# Equivalent to sui, but for targeting remote testnet network only.

# Utility functions.
setup_error() { echo "$*" 1>&2 ; exit 1; }

# Just find the absolute path of the "dtp-dev"
SCRIPT_READLINK="$(readlink -f "$0")"
SCRIPT_NAME="$(basename $SCRIPT_READLINK)"
SCRIPT_DIR="$(dirname $SCRIPT_READLINK)"
DEV_DIR_REL="$SCRIPT_DIR/../../dtp-dev"
DEV_DIR="$(cd "$(dirname "$DEV_DIR_REL")"; pwd)/$(basename "$DEV_DIR_REL")"

# Some other commonly used locations.
SUI_BIN_DIR="$DEV_DIR/sui-testnet/target/debug"

# Files often needed for sui CLI calls
CLIENT_CONFIG="$DEV_DIR/testnet/client.yaml"
KEYSTORE_FILE="$DEV_DIR/testnet/sui.keystore"

mkdir -p "$DEV_DIR/testnet"

# TODO Validate if dtp-dev and sui binary are correct and give advises if not.

# Use the proper config automatically.
SUI_SUBCOMMAND=$1
if [[ "$1" = "client" || "$1" == "console" ]]; then  
  shift 1
  $SUI_BIN_DIR/sui $SUI_SUBCOMMAND --client.config "$CLIENT_CONFIG" "$@"
  exit
fi

if [[ "$1" == "network" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $SUI_BIN_DIR/sui network --help
  fi
  echo
  echo "network command not supported by tsui for remote testnet. Try with sui directly if you think it should work!?"
  exit
fi

if [[ "$1" == "genesis" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $SUI_BIN_DIR/sui genesis --help
  fi
  echo
  echo "genesis command not supported by tsui for remote testnet. Try with sui directly if you think it should work!?"
fi

if [[ "$1" == "start" ]]; then
  if [[ "$2" == "--help" || "$2" == "-h" ]]; then
    $SUI_BIN_DIR/sui start --help
  fi
  echo
  echo
  echo "start command not supported by tsui for remote testnet. Try with sui directly if you think it should work!?"
fi

if [[ "$1" == "keytool" ]]; then
  shift 1
  $SUI_BIN_DIR/sui $SUI_SUBCOMMAND --keystore-path "$KEYSTORE_FILE" "$@"
  exit
fi

# Default
$SUI_BIN_DIR/sui "$@"
