---
protocol-key-pair: I8fF9DhqQ3LB712V2ticI+TWI/IL4hWu2awSSlpu7COu0TD2aPzdeW5L+YzrfpGC4Dw8NPlJBaV9NykNnPZYk8e/C86UwnUfIfHr0J+mgK4YRegU9GnCuRzqFwgdnPyNlLFxBPqcNwhGPLXPnpy5vHaQV5VP0dQUlG4/OXeoMlY=
worker-key-pair: LtVLMzy38Si45qQiH/XCNhL6VT0Cs7Mi7dpM8ALGfifUnd7j3yPHxTAaKtzCqucDiRq+4Ue/cA1AH5KG/iBFjQ==
account-key-pair: AKktU5Q34+kpnYwk2U1ebM147U72kLE97XNywc6fI98arwX1IKuJnlRCgg4mvDYf+kw6WRDpLBicUehkpwuwC9A=
network-key-pair: zVdRHEktVDMsiAw8rrtSp69GbuWmK+xB2wdcerGPieKEai54wP7BQjUd6yTrHUz8S95pwE2oL5zeygb0IKmtjQ==
db-path: /home/olet/.sui/sui_config/authorities_db/aed130f668fcdd796e4bf98ceb7e9182e03c3c34f94905a57d37290d9cf65893c7bf0bce94c2751f21f1ebd09fa680ae1845e814f469c2b91cea17081d9cfc8d94b17104fa9c3708463cb5cf9e9cb9bc769057954fd1d414946e3f3977a83256
network-address: /ip4/127.0.0.1/tcp/45839/http
json-rpc-address: "127.0.0.1:42125"
websocket-address: ~
metrics-address: "127.0.0.1:36649"
admin-interface-port: 40639
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/33609/http
  consensus-db-path: /home/olet/.sui/sui_config/consensus_db/aed130f668fcdd796e4bf98ceb7e9182e03c3c34f94905a57d37290d9cf65893c7bf0bce94c2751f21f1ebd09fa680ae1845e814f469c2b91cea17081d9cfc8d94b17104fa9c3708463cb5cf9e9cb9bc769057954fd1d414946e3f3977a83256
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/41613/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/41083/http
    network_admin_server:
      primary_network_admin_server_port: 42429
      worker_network_admin_server_base_port: 41605
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:42421"
genesis:
  genesis-file-location: /home/olet/.sui/sui_config/genesis.blob
