---
protocol-key-pair: Idxfva0pArgtv9tIp2mH26cTsh50nWc9k369iChZ+AmiKRGb+AtYjCWgQkDA+zSrYe5KNQWJSUy2rXLJ2stY9gT0ARPSbG/mBAJh5BhBnN0LxDdw4T+ywpWT74yQNCcjOcMmZ2QvJAkG79kByBX6HMHxzAw6OYbKDOlSfbYWS5s=
worker-key-pair: tPLuKqIsH7wpKUt74AcOBK002zZXDRejmQTc8gl1hnbqsNWO/1O9j4tgETASEyev8r4V4CwG1gApuflNNMy04w==
account-key-pair: AD8ZamfqUnRZNCXSuYTBc/+1XqOLj4N8VnglJgaMjqkdKAe3PIy4xkPE8N8yHrYxiFqGQMgySMGJdVTKHxyrLww=
network-key-pair: S8n0+JsCFoNZklXuQ3MM1eKPNLRRRjMnrxsOhoM0GdSVqw/YJUS6syq+1TzB2tDhzXkrbE/BAib2DjbGDDoryA==
db-path: /home/olet/.sui/sui_config/authorities_db/a229119bf80b588c25a04240c0fb34ab61ee4a350589494cb6ad72c9dacb58f604f40113d26c6fe6040261e418419cdd0bc43770e13fb2c29593ef8c9034272339c32667642f240906efd901c815fa1cc1f1cc0c3a3986ca0ce9527db6164b9b
network-address: /ip4/127.0.0.1/tcp/44853/http
json-rpc-address: "127.0.0.1:38183"
websocket-address: ~
metrics-address: "127.0.0.1:45411"
admin-interface-port: 44327
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/37835/http
  consensus-db-path: /home/olet/.sui/sui_config/consensus_db/a229119bf80b588c25a04240c0fb34ab61ee4a350589494cb6ad72c9dacb58f604f40113d26c6fe6040261e418419cdd0bc43770e13fb2c29593ef8c9034272339c32667642f240906efd901c815fa1cc1f1cc0c3a3986ca0ce9527db6164b9b
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/44033/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/35005/http
    network_admin_server:
      primary_network_admin_server_port: 44057
      worker_network_admin_server_base_port: 44779
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:35485"
genesis:
  genesis-file-location: /home/olet/.sui/sui_config/genesis.blob
