---
protocol-key-pair: OMjYhnMe8H6sWavjzMhcujBbZ4YPQ3aQSLK26X5FV1CGCjTVTOHxx35BN/x4qZUt2cCe1ug2KEq95xaF9OUZVyI6znaZTVNh31fLThLjRAcTZDMJ/WwXve0LZJ7BjZ0h+ZalA9E9qG95rubMua53fJAO2l4U4yHaFCkvsElW65w=
worker-key-pair: x8ZmWe9DSBOyTGHSBTL0mCZMp7re4z9mB6akaiWhkpE9t+eSt+ZxB7lfBqMScCavkVgNqK3bM4LVHrVersXvFA==
account-key-pair: AM/7PABjua09twBfpT267IrS/t3AHCqNN8pYdc2YjVWE9r9ziY0hw7pkJSQLQHOAxrYTSY2BxCC87VMCTehADhU=
network-key-pair: re5iH+EFqWg5bKckZZ/XINwDuPF+tdD3f3vnjAEMJRw8Vp0+tyRxy3oQk00Rdk4QkBomBAFhmg5+krDZ0q1uVg==
db-path: /home/olet/.sui/sui_config/authorities_db/860a34d54ce1f1c77e4137fc78a9952dd9c09ed6e836284abde71685f4e51957223ace76994d5361df57cb4e12e3440713643309fd6c17bded0b649ec18d9d21f996a503d13da86f79aee6ccb9ae777c900eda5e14e321da14292fb04956eb9c
network-address: /ip4/127.0.0.1/tcp/36587/http
json-rpc-address: "127.0.0.1:41569"
websocket-address: ~
metrics-address: "127.0.0.1:38153"
admin-interface-port: 40567
consensus-config:
  consensus-address: /ip4/127.0.0.1/tcp/33939/http
  consensus-db-path: /home/olet/.sui/sui_config/consensus_db/860a34d54ce1f1c77e4137fc78a9952dd9c09ed6e836284abde71685f4e51957223ace76994d5361df57cb4e12e3440713643309fd6c17bded0b649ec18d9d21f996a503d13da86f79aee6ccb9ae777c900eda5e14e321da14292fb04956eb9c
  timeout-secs: 60
  narwhal-config:
    header_num_of_batches_threshold: 32
    max_header_num_of_batches: 1000
    max_header_delay: 100ms
    gc_depth: 50
    sync_retry_delay: 5000ms
    sync_retry_nodes: 3
    batch_size: 500000
    max_batch_delay: 100ms
    block_synchronizer:
      range_synchronize_timeout: 30000ms
      certificates_synchronize_timeout: 30000ms
      payload_synchronize_timeout: 30000ms
      payload_availability_timeout: 30000ms
      handler_certificate_deliver_timeout: 30000ms
    consensus_api_grpc:
      socket_addr: /ip4/127.0.0.1/tcp/40257/http
      get_collections_timeout: 5000ms
      remove_collections_timeout: 5000ms
    max_concurrent_requests: 500000
    prometheus_metrics:
      socket_addr: /ip4/127.0.0.1/tcp/39269/http
    network_admin_server:
      primary_network_admin_server_port: 41203
      worker_network_admin_server_base_port: 43535
enable-event-processing: false
enable-checkpoint: false
enable-reconfig: false
grpc-load-shed: ~
grpc-concurrency-limit: 20000000000
p2p-config:
  listen-address: "127.0.0.1:40151"
genesis:
  genesis-file-location: /home/olet/.sui/sui_config/genesis.blob
