[package]
name = "dtp-dev-app"
version = "0.1.0"
edition = "2021"

[dependencies]
sui-sdk = { workspace=true }
anyhow = { workspace=true }
tokio = { workspace=true }

dtp-sdk = { path = "../dtp-sdk/" }
