name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  diff:
    runs-on: [ubuntu-latest]
    outputs:
      isDoc: ${{ steps.diff.outputs.isDoc }}
    steps:
    - uses: actions/checkout@v3
    - name: Detect Changes
      uses: './.github/actions/diffs'
      id: diff

  spelling:
    name: Lint documentation
    needs: diff
    if: needs.diff.outputs.isDoc == 'true'
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Spell Check Docs
      uses: crate-ci/typos@master
      with:
        files: ./doc ./*.md
